name: wantok_ui
description: Shared Wantok Services Flutter design system.
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.13.5
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  wantok_core:
    path: ../wantok_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
